### ISSUE TITLE
[OOB 5.6]System hang up by pressing SW3 on K64F

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-os-example-uvisor#56]
### Description

- Type: To be confirm
- Related issue: none
- Priority: Minor

### ## ISSUE

**Target Platform:**
FRDM K64F

**Toolchain Version:**
GCC_ARM V6
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors 6-2017-q1-update) 6.3.1 20170215 (release) [ARM/embedded-6-branch revision 245512

**mbed-cli Version:**
1.2.0

**mbed-os sha:**
mbed-os-example-uvisor (079c015)
`- mbed-os (a4056fb8bf3e)

**DAPLink Version:**
Version: 0226
Build:   Aug 24 2015 17:06:30
Git Commit SHA: 27a236b9fe39c674a703c5c89655fbd26b8e27e1
Git Local mods: Yes

**Expected Behavior:**
No impact to normal behavior by pressing SW3 button.

**Actual Behavior:**
When the SW3 button is pressed, the system will hang up.
I did not see any code relevant to SW3.

```
Main loop count: 5592

Pressed switch, printing from interrupt - LED now on.

Main loop count: 5593
Main loop count: 5594
Main loop count: 5595

Pressed switch, printing from interrupt - LED now off.

Main loop count: 5596
Main loop count: 5597
Main loop count: 5598
Main loop count: 5599
```

**Step to reproduce:**
```
$ mbed import mbed-os-example-uvisor
$ cd mbed-os-example-uvisor
$ mbed update mbed-os-5.6-oob
$ mbed compile -m K64F -t GCC_ARM -f
```

**Comment by Patater** [comment]
SW3 is NMI. The default handler for NMI (when uVisor is enabled) is an infinite loop. This is expected behavior.
