### ISSUE TITLE
[OOB 5.6] Document link is broken (404 error)

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-uvisor#58]
https://github.com/ARMmbed/mbed-os-example-uvisor#debug

Document link to the ```Debugging uVisor on mbed OS``` is broken.

Incorrect : https://github.com/ARMmbed/uvisor/blob/master/docs/api/DEBUGGING.md
Correct   : https://github.com/ARMmbed/uvisor/blob/master/docs/lib/DEBUGGING.md

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-447
