### ISSUE TITLE
[OoB-5.9]: Deprecation warning is not visible enough.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-uvisor#89]
The warning message must appear on the source files (main.cpp) as well for cases where not everyone in the outside world reads the README first :-) ..

Also, (side note) deprecation warning has been added to master branch. This is only a note but during OoB, changes are expected on the OoB branch and no further changes to master until the release.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-700

**Comment by alzix** [comment]
fixed via https://github.com/ARMmbed/mbed-os-example-uvisor/commit/8b313c1928f45822a00d88d2cf09cecb0bd65254
