### ISSUE TITLE
Export to make_gcc_arm doesn't work for mbed-os-5.3.0-rc3

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/mbed-os-example-uvisor#9]
The export and compilation works fine, but the LED stays off and there's nothing on serial.

**Comment by bulislaw** [comment]
The same issue with all other uvisor examples.

**Comment by AlessandroA** [comment]
Hi @bulislaw, there was a misunderstanding. Exporters are out of the scope of OOB testing for this release. See the related known issue: http://jira.arm.com/browse/IOTMORF-510. The spreadsheet has been updated as well with 'Don't test'. Thanks for reporting though!

**Comment by MarceloSalazar** [comment]
https://github.com/ARMmbed/mbed-os-example-uvisor/pull/26
